name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build all platforms
      run: |
        dirname="/var/www/builds/$(date '+%F_%H-%M-%S')"
        ln -sfn $dirname /var/www/builds/latest
        go tool dist list | while read line
        do
          os=$(echo $line | cut -d "/" -f 1)
          arch=$(echo $line | cut -d "/" -f 2)
          outfile="$dirname/$os/$arch/bananascript"
          if [ "$os" = "windows" ]; then
            outfile="${outfile}.exe"
          fi
          echo "Building $line..."
          GOOS="$os" GOARCH="$arch" go build -o $outfile src/main.go || true
        done
